search:
  # base dir path (from root if relative)
  base: sphinx_data

  # Search daemon base url
  #api_endpoint: http://localhost:9304/

  # Set `false` if sphinx deamons should not be started (when remote host used)
  is_local: true

  # Run `optimize index` against all tables after reindex
  #optimize: true

  # name or path to searchd binary
  #bin: searchd

  searchd:
    workers:      thread_pool
    binlog_path:  binlog
    pid_file:     pid_file
    listen:       searchd.sock:mysql41

  indexes:
    # Default configs to inherit. Done to simplify global modifications -
    # morphology, charset table and others.
    _default_base:
      type: rt

    '_default_topic: _default_base':
      index_exact_words: 1

      min_infix_len: 2

    '_default_content: _default_base':
      index_exact_words: 1

      html_strip: 1
      html_index_attrs: a=href;
      html_remove_elements: blockquote
