search:
  # base dir path (from root if relative)
  base: sphinx_data

  # Search daemon base url
  #api_endpoint: http://localhost:9304/

  # Set `false` if sphinx deamons should not be started (when remote host used)
  is_local: true

  # name or path to searchd binary
  #bin: searchd

  searchd:
    workers:      thread_pool
    binlog_path:  binlog
    pid_file:     pid_file
    listen:       searchd.sock:mysql41
    seamless_rotate: 1

  indexes:
    # Default config to inherit. Done to simplify global modifications -
    # morphology, charset table and others.
    _default:
      type: rt

    # Commons for content indexes
    # (there can be other indexes, for typing tooltips etc)
    '_default_content : _default':
      rt_field: [ content ]
      rt_attr_timestamp: [ ts ]
      rt_attr_string: [ objectid, parentid ]
