search:
  # base dir path (from root if relative)
  base: sphinx_data

  # Search daemon base url
  #api_endpoint: http://localhost:9304/

  # Set `false` if sphinx deamons should not be started (when remote host used)
  is_local: true

  # name or path to searchd binary
  #bin: searchd

  # List of tasks to run when starting reindex in admin
  reindex_tasks: []

  searchd:
    read_timeout: 5
    max_children: 5
    binlog_path:  binlog
    pid_file:     pid_file
    listen:       searchd.sock:mysql41

  indexes:
    # default индекс будет всегда пустым, остальные индексы наследуются от него
    default:
      type: rt
      preopen: 1
      #morphology: lemmatize_en,lemmatize_ru,lemmatize_de
      #charset_table: 0..9, _, english, russian
      #ignore_chars: '-, U+AD'
      #min_stemming_len: 4
      #min_word_len: 1
      #stopwords: /path/to/stopwords.txt
      #wordforms: /path/to/wordforms.txt

      # Default fields
      rt_field: [ content ]
      rt_attr_timestamp: [ ts ]
      rt_attr_string: [ objectid, parentid ]
